require("owen.remap")
require("owen.set")
require("owen.packer")

require("owen.after.plugin.telescope")
require("owen.after.plugin.colors")
require("owen.after.plugin.lsp")
require("owen.after.plugin.treesitter")
require("owen.after.plugin.fugitive")
require("owen.after.plugin.undotree")
require("owen.after.plugin.feline")
