require("plugins.colors")
require("plugins.telescope")
require("plugins.lsp")
require("plugins.ui")
require("plugins.neotree")
require("plugins.cmp")
require("plugins.treesitter")
require("plugins.videre")
require("plugins.undotree")
require("plugins.flutter")
require("plugins.lsp_sig")
require("plugins.spell")
require("plugins.scrolleof")
require("plugins.renamer")
require("plugins.java")
require("plugins.roslyn")

